backend:
  name: git-gateway
  repo: brienpacholec/hiddenfenceco

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - label: "Posts"
    name: "posts"
    folder: "posts"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Slug", name: "slug", widget: "string"}
      - {label: "Excerpt", name: "excerpt", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "date"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Display", name: "Display", widget: "boolean"}
  - label: "Page Content"
    name: "page_content"
    files:
      - label: "Home Page"
        name: "home"
        file: "page_content/home.md"
        fields: 
          - { label: "Featured Image", name: "thumbnail", widget: "image"}
          - { label: "Body", name: "body", widget: "markdown" }
      - label: "About Page"
        name: "about"
        file: "page_content/about.md"
        fields: 
          - {label: "Body", name: "body", widget: "markdown"}
      - label: "Services Page"
        name: "services"
        file: "page_content/services.md"
        fields: 
          - {label: "Body", name: "body", widget: "markdown"}
      - label: "Reviews Page"
        name: "reviews"
        file: "page_content/reviews.md"
        fields: 
          - {label: "Body", name: "body", widget: "markdown"}
      - label: "Contact Page"
        name: "contact"
        file: "page_content/contact.md"
        fields: 
          - {label: "Body", name: "body", widget: "markdown"}
      - label: "Hero Data"
        name: "hero_data"
        file: "page_content/hero_data.md"
        fields: 
          - { label: "Featured Image", name: "thumbnail", widget: "image"}
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Subtitle", name: "subtitle", widget: "string" }

